package com.example.mybatis02.model;

import java.io.Serializable;
import java.util.Date;

public class QaEmploy implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_employ.EMPLOY_ID
     *
     * @mbg.generated
     */
    private Integer employId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_employ.EMPLOY_NAME
     *
     * @mbg.generated
     */
    private String employName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_employ.EMPLOY_CREATION_DT
     *
     * @mbg.generated
     */
    private Date employCreationDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_employ.EMPLOY_UPDATE_DT
     *
     * @mbg.generated
     */
    private Date employUpdateDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_employ.EMPLOY_DELETED_FLAG
     *
     * @mbg.generated
     */
    private Boolean employDeletedFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_employ.EMPLOY_GROUP
     *
     * @mbg.generated
     */
    private Integer employGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qa_employ
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_employ.EMPLOY_ID
     *
     * @return the value of qa_employ.EMPLOY_ID
     *
     * @mbg.generated
     */
    public Integer getEmployId() {
        return employId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_employ.EMPLOY_ID
     *
     * @param employId the value for qa_employ.EMPLOY_ID
     *
     * @mbg.generated
     */
    public void setEmployId(Integer employId) {
        this.employId = employId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_employ.EMPLOY_NAME
     *
     * @return the value of qa_employ.EMPLOY_NAME
     *
     * @mbg.generated
     */
    public String getEmployName() {
        return employName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_employ.EMPLOY_NAME
     *
     * @param employName the value for qa_employ.EMPLOY_NAME
     *
     * @mbg.generated
     */
    public void setEmployName(String employName) {
        this.employName = employName == null ? null : employName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_employ.EMPLOY_CREATION_DT
     *
     * @return the value of qa_employ.EMPLOY_CREATION_DT
     *
     * @mbg.generated
     */
    public Date getEmployCreationDt() {
        return employCreationDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_employ.EMPLOY_CREATION_DT
     *
     * @param employCreationDt the value for qa_employ.EMPLOY_CREATION_DT
     *
     * @mbg.generated
     */
    public void setEmployCreationDt(Date employCreationDt) {
        this.employCreationDt = employCreationDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_employ.EMPLOY_UPDATE_DT
     *
     * @return the value of qa_employ.EMPLOY_UPDATE_DT
     *
     * @mbg.generated
     */
    public Date getEmployUpdateDt() {
        return employUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_employ.EMPLOY_UPDATE_DT
     *
     * @param employUpdateDt the value for qa_employ.EMPLOY_UPDATE_DT
     *
     * @mbg.generated
     */
    public void setEmployUpdateDt(Date employUpdateDt) {
        this.employUpdateDt = employUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_employ.EMPLOY_DELETED_FLAG
     *
     * @return the value of qa_employ.EMPLOY_DELETED_FLAG
     *
     * @mbg.generated
     */
    public Boolean getEmployDeletedFlag() {
        return employDeletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_employ.EMPLOY_DELETED_FLAG
     *
     * @param employDeletedFlag the value for qa_employ.EMPLOY_DELETED_FLAG
     *
     * @mbg.generated
     */
    public void setEmployDeletedFlag(Boolean employDeletedFlag) {
        this.employDeletedFlag = employDeletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_employ.EMPLOY_GROUP
     *
     * @return the value of qa_employ.EMPLOY_GROUP
     *
     * @mbg.generated
     */
    public Integer getEmployGroup() {
        return employGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_employ.EMPLOY_GROUP
     *
     * @param employGroup the value for qa_employ.EMPLOY_GROUP
     *
     * @mbg.generated
     */
    public void setEmployGroup(Integer employGroup) {
        this.employGroup = employGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qa_employ
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", employId=").append(employId);
        sb.append(", employName=").append(employName);
        sb.append(", employCreationDt=").append(employCreationDt);
        sb.append(", employUpdateDt=").append(employUpdateDt);
        sb.append(", employDeletedFlag=").append(employDeletedFlag);
        sb.append(", employGroup=").append(employGroup);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}