package com.example.mybaitis.dao;

import com.example.mybaitis.model.QaEmploy;
import java.util.List;

public interface QaEmployMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qa_employ
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer employId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qa_employ
     *
     * @mbg.generated
     */
    int insert(QaEmploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qa_employ
     *
     * @mbg.generated
     */
    QaEmploy selectByPrimaryKey(Integer employId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qa_employ
     *
     * @mbg.generated
     */
    List<QaEmploy> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qa_employ
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QaEmploy record);
}